lang: en

title: coronavirusisrael.live
description: >- # this means to ignore newlines until "baseurl:"
  coronavirusisrael.live is a web app where you will be able to track the spread of Coronavirus Covid-19 outbreak worldwide,
  browse an interactive map, view stats and charts, check affected regions in real-time and more.
keywords: "Corona, Coronavirus, israel, covid 19, Coronavirus updates, live status, news"
author: "Meir Roth"
url:  https://coronavirusisrael.live/
baseurl:  # the subpath of your site, e.g. /blog
permalink: pretty
environment: development
google-tracking-id: "UA-161377905-4" # Google Tracking ID and property number
theme-color: '#751010'

collections:
  posts:
    output: false

sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-minifier
- jekyll-autoprefixer
autoprefixer:
  browsers:
  - last 2 versions
